apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: ckan-solr
  name: ckan-solr
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ckan-solr
    spec:
      containers:
      - image: ckan-solr
        name: ckan-solr
        resources: {}
      restartPolicy: Always
status: {}
